# Generated by Django 5.2.5 on 2025-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('note', models.TextField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('note', models.TextField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
