# Generated by Django 5.2.5 on 2025-10-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expense_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='expense_type',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='income_type',
        ),
    ]
