# Generated by Django 4.2.23 on 2025-09-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration_Form',
            new_name='Registration',
        ),
    ]
