# Generated by Django 4.2.23 on 2025-09-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_registration_form_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
